POST https://node-do-zero-jg1y.onrender.com/books
Content-Type: application/json

{
    "title": "O pequeno príncipe",
    "description": "livro de fantasia",
    "author": "Antonie de Saint-Exupéry",
    "pages": 95
}

###

GET  https://node-do-zero-jg1y.onrender.com/books

###

PUT https://node-do-zero-jg1y.onrender.com/books/f938d679-ef39-4deb-b77e-df8a7ee90b61
Content-Type: application/json

{
    "title": "Casa de céu e sopro",
    "description": "Livro sobre fantasia",
    "author": "Sarah Mass",
    "pages": "922"
}

###

DELETE https://node-do-zero-jg1y.onrender.com/books/a2508158-222b-40d4-86fe-95012d530221